site: YAR
title: YAR
description: >-
  I'm Amirreza, I do stuffs with data and sometimes write about it here.
googlewebfonts: Fira+Code:wght@400;500;700
lang: en-US
timezone: Rome
data-theme: dark # default theme "dark" | "light"

author:
  name: Amirreza
  bio: Data Scientist
  username: 9amirreza6 # general username
  github: 9amirreza6 # github username
  twitter: 9amirreza6 # twitter username
  email: amirreza@outlook.it # email adress

# URL settings
url: "https://9amirreza6.github.io/" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


